language: php
sudo: false
php:
  - 7.1
install:
  - composer self-update
  - composer install
script:
  - php vendor/bin/phpunit
after_success:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.1/coveralls.phar -O coveralls.phar
  - php coveralls.phar -v
